 my @DummyQueryResults = (
   {
     Avail    => "10",
     Demand   => "0",
     InUse    => "0",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "6",
     InUse    => "6",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "6",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "12",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "12",
     Demand   => "14",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "14",
     Demand   => "16",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "8",
     Demand   => "6",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "8",
     Demand   => "10",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "8",
     Demand   => "6",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "8",
     Demand   => "10",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "8",
     Demand   => "25",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "12",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "12",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "14",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "16",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
   {
     Avail    => "10",
     Demand   => "8",
     InUse    => "8",
     Shortage => "0",
   },
 );
